image:
  file: .gitpod.Dockerfile

ports:
  - port: 8888
    protocol: "http"

tasks:
  - command: |
      echo "Excluding unnecessary files..."
      rm -rf images Dockerfile README.md jupyter_server_config.json LICENSE